[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet = "CjQhTWFwN7jQYo2SUjhkdi3R94eg94sGAU2cRkPAzkPk"
puppet_master = "8r1v8mcoxuG3noMMdVcwfS7X2hbLnNLURksDTj4CpM4e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



[test.validator]
url = "http://localhost:8899"
rpc_port = 8899

[faucet]
port = 9901


